version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

    commands:
      # install npm
      - npm install --force

  build:
    commands:
      # run build script
      - npm run-script build

artifacts:
  files:
    - .elasticbeanstalk/**/*
    - build/**/*
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - buildspec.yml
    - scripts/**/*
